### ISSUE TITLE
how to build  redis src  in

### ISSUE THREAD

**Issue by icetech233** [zkteco-home/redis#1]
how ? build src in windows sys

**Comment by icetech233** [comment]
how  ?  build src in windows sys

**Comment by my9988** [comment]
it is very very complicated to compile under windows system.i woked on this for sererval months.there are many difference between linux and windows,once stable,i will public source code

**Comment by zkteco-home** [comment]
> how ? build src in windows sys

it is very very complicated to compile under windows system.i woked on this for sererval months.there are many difference between linux and windows,once stable,i will public source code.

**Comment by likev** [comment]
please contribute directly to https://github.com/tporadowski/redis/tree/win-6.2

**Comment by oldmud0** [comment]
This is sketchy. I wouldn't download binaries without backing source code.

**Comment by zkteco-home** [comment]
> This is sketchy. I wouldn't download binaries without backing source code.

It's up to you,maybe it is not free to download in the future.
